Tecnowise/Models/BaseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace Tecnowise.Models
{
    public abstract class BaseModel
    {
        public int Id { get; set; }
    }
}

Tecnowise/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Tecnowise.Models
{
    public class Cliente:BaseModel
    {
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Municipio { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }

        public Cliente()
        {
            Nome = "";
            Email = "";
            Telefone = "";
            Endereco = "";
            Bairro = "";
            Municipio = "";
            UF = "";
            CEP = "";
        }
    }
}

Tecnowise/Models/ErrorViewModel.cs
using System;

namespace Tecnowise.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tecnowise/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Tecnowise.API;
using Tecnowise.Models;

namespace Tecnowise.Controllers
{
    public class ClienteController : Controller
    {
        ClienteApi api = new ClienteApi();

        public IActionResult Cadastro(int id)
        {
            if (id == 0)
            {
                var novo = api.Set(new Cliente());
                id = novo.Id;
            }

            return View(api.Get(id));
        }

        public IActionResult Listagem()
        {
            var lista = api.GetList();
            return View(lista);
        }

        public IActionResult Salvar(Cliente modelo)
        {
            if (api.Update(modelo))
                return RedirectToAction("Listagem");

            return BadRequest();
        }

        public IActionResult Cancelar(int id)
        {
            var cliente = api.Get(id);
            if (string.IsNullOrEmpty(cliente.Nome) && string.IsNullOrEmpty(cliente.Email)
                     && string.IsNullOrEmpty(cliente.Telefone) && string.IsNullOrEmpty(cliente.Endereco)
                     && string.IsNullOrEmpty(cliente.Bairro) && string.IsNullOrEmpty(cliente.Municipio)
                     && string.IsNullOrEmpty(cliente.UF) && string.IsNullOrEmpty(cliente.CEP))
            {
                api.Delete(id);
            }
            return RedirectToAction("Listagem");
        }

        public IActionResult Delete(Cliente modelo)
        {
            if (modelo != null)
            {
                if (api.Delete(modelo.Id))
                    return RedirectToAction("Listagem");

                return BadRequest();
            }

            return BadRequest();
        }
    }
}

Tecnowise/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Tecnowise.Models;

namespace Tecnowise.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tecnowise/Views/Cliente/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro";
}
@model Cliente

<h3>Cadastro</h3>
<form asp-action="salvar" method="post">

    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="form-group col-md-1">
                    <label class="control-label" for="nomeId">Id</label>
                    <input type="text" class="form-control" id="idCliente" placeholder="ID"
                           asp-for="@Model.Id" readonly>
                </div>
                <div class="form-group col-md-11">
                    <label class="control-label" for="nomeCliente">Nome do Cliente</label>
                    <input type="text" class="form-control" id="nomeCliente" placeholder="Nome do Cliente"
                           asp-for="@Model.Nome" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label" for="email">Email</label>
                    <input type="email" class="form-control" id="email" placeholder="Email"
                           asp-for="@Model.Email" required>
                </div>
                <div class="form-group col-md-6">
                    <label class="control-label" for="telefone">Telefone</label>
                    <input type="text" class="form-control" id="telefone" placeholder="Telefone"
                           asp-for="@Model.Telefone" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label class="control-label" for="cep">CEP</label>
                    <input type="text" class="form-control" id="cep" placeholder="CEP"
                           asp-for="@Model.CEP" aria-describedby="descricao" required>
                    <small id="descricao" class="text-muted">
                        Dica: Digite o CEP e tecle TAB.
                    </small>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label class="control-label" for="endereco">Endereço</label>
                    <input type="text" class="form-control" id="endereco" placeholder="Endereço"
                           asp-for="@Model.Endereco" required>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-5">
                    <label class="control-label" for="bairro">Bairro</label>
                    <input type="text" class="form-control" id="bairro" placeholder="Bairro"
                           asp-for="@Model.Bairro" required>
                </div>

                <div class="form-group col-md-4">
                    <label class="control-label" for="municipio">Município</label>
                    <input type="text" class="form-control" id="municipio" placeholder="Município"
                           asp-for="@Model.Municipio" required>
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label" for="UF">UF</label>
                    <select id="uf" class="form-control single-select" name="UF"
                            asp-for="@Model.UF" required>
                        <option selected value="">[Selecione o estado]</option>
                        <option value="AC">Acre</option>
                        <option value="AL">Alagoas</option>
                        <option value="AP">Amapá</option>
                        <option value="AM">Amazonas</option>
                        <option value="BA">Bahia</option>
                        <option value="CE">Ceará</option>
                        <option value="DF">Distrito Federal</option>
                        <option value="ES">Espírito Santo</option>
                        <option value="GO">Goiás</option>
                        <option value="MA">Maranhão</option>
                        <option value="MT">Mato Grosso</option>
                        <option value="MS">Mato Grosso do Sul</option>
                        <option value="MG">Minas Gerais</option>
                        <option value="PA">Pará</option>
                        <option value="PB">Paraíba</option>
                        <option value="PR">Paraná</option>
                        <option value="PE">Pernambuco</option>
                        <option value="PI">Piauí</option>
                        <option value="RJ">Rio de Janeiro</option>
                        <option value="RN">Rio Grande do Norte</option>
                        <option value="RS">Rio Grande do Sul</option>
                        <option value="RO">Rondônia</option>
                        <option value="RR">Roraima</option>
                        <option value="SC">Santa Catarina</option>
                        <option value="SP">São Paulo</option>
                        <option value="SE">Sergipe</option>
                        <option value="TO">Tocantins</option>
                    </select>
                </div>
            </div>

            <div class="buttons">
                <div class="form-group">
                    <button type="submit"
                            class="btn btn-success">
                        Salvar
                    </button>
                </div>
                <div class="form-group">
                    <a class="btn btn-success" asp-action="Cancelar" asp-route-id="@Model.Id">
                        Cancelar
                    </a>
                </div>
                @*<div class="form-group">
                    <a class="btn btn-success" asp-action="Delete">
                        Excluir
                    </a>
                </div>*@
            </div>
        </div>
    </div>
</form>

<script src="~/js/cep.js">
</script>

Tecnowise/Views/Cliente/Listagem.cshtml
@model IEnumerable<Tecnowise.Models.Cliente>

@{
    ViewData["Title"] = "Listagem";
}

<h1>Clientes</h1>

<p>
    <a asp-action="Cadastro">Cadastrar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.ActionLink("Editar", "Cadastro", new { id=item.Id} ) |
                @Html.ActionLink("Excluir", "Delete", new { id = item.Id} ) |
                <!-- Button trigger modal -->
                <a data-toggle="modal" data-target="#exampleModal">
                    Detalhes
                </a>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">@item.Nome</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="row details">
                                    <div>Email: @item.Email</div>
                                    <div>Telefone: @item.Telefone</div>
                                    <div>CEP: @item.CEP</div>
                                    <div>Endereço: @item.Endereco</div>
                                    <div>Bairro: @item.Bairro</div>
                                    <div>Municipio: @item.Municipio</div>
                                    <div>UF: @item.UF</div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
        }
    </tbody>
</table>



Tecnowise/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tecnowise</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    @*<script src="https://kendo.cdn.telerik.com/2019.3.1023/js/jquery.min.js"></script>*@
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Cliente" asp-action="Listagem">
                    <img class="logo" src="https://grupotecnowise.com.br/wp-content/uploads/2019/08/TW-logo.png" alt="Grupo Tecnowise" width="500" height="84">
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Tecnowise - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>